In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0, 8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
#Get Dimension of NumPy arrays #b would have two arrays bc of the two lists made
b.ndim

2

In [9]:
#Get shape #b would have two rows and three columns 
b.shape

(2, 3)

In [10]:
#Get Type
b.dtype

dtype('float64')

In [12]:
#Get Size
a.itemsize

8

In [13]:
#Get Total Size 
a.nbytes

24

### Accessing/Changing Specific Elements, Rows and Columns etc. 

In [16]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]]) #2 by 7 array
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
#Get a specific element [r,c]
# if you want to get the 13, in python index that is 1, and it is in the 5th position
a[1,5] # can also use a[1,-2]

13

In [18]:
# Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#Get a specific column 
a[:,2]

array([ 3, 10])

In [21]:
# [startindex:endindex:stepsize] #start at 2 and end at 6 but every other number 
a[0, 1:6:2] # or a[0, 1:-1:2]

array([2, 4, 6])

In [22]:
# Change access (if you want to change that 13 to a 20)
a[1,5] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [23]:
# Change access (if you want to change the [3,10])

a[:,2] = [1,2]
print(a)


[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [38]:
#3-d example 
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
# Get specific Element (work outside in) #wanted to get the 4 (so first paranthesis which would be 0, second section which would be 1, and then secons number which would be 1)
c[0,1,1]

4

In [40]:
# Get [3,4] and [7,8]
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [41]:
#Replace
c[:,1,:] = [[9,9],[8,8]] #need to have [2,2] not [2,2,2]
print (c)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Intializing Different Types of Arrays 

In [43]:
#ALL 0s Matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [46]:
#ALL 1s Matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [47]:
# can specify data type
np.ones ((4,2), dtype = "int32")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [48]:
# Any other number (uses 2 by 2 and the number you want to input)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [50]:
# Any other number (full_like) from a from the beginning 
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [52]:
#Random Decimal Numbers
np.random.rand(4,2,3)

array([[[0.20600882, 0.51894305, 0.06741109],
        [0.66591789, 0.63864336, 0.89701923]],

       [[0.57755965, 0.17068749, 0.16344487],
        [0.76229821, 0.08918601, 0.29866629]],

       [[0.9504401 , 0.70953687, 0.92783446],
        [0.92045029, 0.80007522, 0.13716446]],

       [[0.89857777, 0.29825575, 0.34318337],
        [0.92067247, 0.12871813, 0.47843227]]])

In [53]:
#Random integer values from integers between 0 to 6
np.random.randint(7, size = (3,3))

array([[4, 3, 0],
       [1, 5, 5],
       [1, 6, 4]])

In [54]:
np.random.randint(4,7, size = (3,3)) #from 4 to 7

array([[4, 5, 4],
       [6, 4, 6],
       [6, 6, 5]])

In [55]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
#Repeat array a few times 
arr = np.array([[1,2,3]])
rl = np.repeat(arr,3,axis = 0)
print (rl)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [60]:
# Get an array with 5 by 5 (how to print the bottom array)
output = np.ones((5,5))
print (output)

z = np.zeros((3,3))
z[1,1] = 9
print (z)

output [1:4,1:4]= z
print (output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!

In [63]:
#copy array 
d = np.array ([1,2,3])
e= d.copy()
e[0] = 100

print (d)
print(e)

[1 2 3]
[100   2   3]


# MATHEMATICS

In [66]:
a = np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [67]:
a+2

array([3, 4, 5, 6])

In [68]:
a-2

array([-1,  0,  1,  2])

In [69]:
a*2

array([2, 4, 6, 8])

In [70]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [72]:
a+=2
a

array([5, 6, 7, 8])

In [73]:
b = np.array([1,0,1,0])

a+b

array([6, 6, 8, 8])

In [74]:
#take sin of values

np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [75]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [82]:
a = np.ones((2,3)) 
print(a)

b = np.full ((3,2),2)
print (b)

#matrix multiplication function 
np.matmul (a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [83]:
# Find the determinant 
c = np.identity (3)
np.linalg.det(c)

1.0

In [84]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [85]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
# min 
np.min(stats)

1

In [87]:
#max
np.max(stats)

6

In [88]:
#min of first row and second row 
np.min(stats, axis = 1)

array([1, 4])

In [89]:
# sum of all elements in matrix 
np.sum(stats)

21

In [90]:
# sum of first and second row 
np.sum(stats, axis = 0)

array([5, 7, 9])

### Reorganizing Arrays

In [91]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print (before)

[[1 2 3 4]
 [5 6 7 8]]


In [92]:
#before = np.array([[1,2,3,4], [5,6,7,8]])
#print (before)

after = before.reshape((8,1))
print (after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [94]:
#Vertically stacking vectors/matrices

v1= np.array([1,2,3,4])
v2 = np.array ([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
#Horizontal stack 

h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [108]:
print (h1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [109]:
print (h2)

[[1. 1.]
 [1. 1.]]


In [110]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Misc 

### Load Data From File 

In [111]:
#load data into numpy array 

# video: https://www.youtube.com/watch?v=QUT1VHiLmmI

### Concatenation of Arrays 

In [112]:
x = np.array([1,2,3])
y= np.array ([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

### Splitting of Arrays 

In [113]:
x = [1,2,3,4,5,99,4,5,3]

x1,x2, x3 = np.split(x, [3,5])

print(x1,x2,x3)

[1 2 3] [4 5] [99  4  5  3]


### Reciprocal Values Calc

In [117]:
np.random.seed(0)

In [118]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [119]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

print(big_array)

2.52 s ± 31.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [120]:
big_array

array([45, 48, 65, ..., 93, 62, 19])

In [121]:
# Outer Products 

In [122]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])